/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__downloader_dll
#define __PYX_HAVE__downloader_dll

#include "Python.h"

#ifndef __PYX_HAVE_API__downloader_dll

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int download_from_url(char const *);
__PYX_EXTERN_C int delete_file(char const *);

#endif /* !__PYX_HAVE_API__downloader_dll */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initdownloader_dll(void);
#else
PyMODINIT_FUNC PyInit_downloader_dll(void);
#endif

#endif /* !__PYX_HAVE__downloader_dll */